["61xx"]
desc = "正常 需发 GET RESPONSE 命令（读取指令 00C00000xx）"

["6200"]
desc = "警告 信息未提供"

["6281"]
desc = "警告 回送数据可能"

["6282"]
desc = "警告 文件长度小于 Le"

["6283"]
desc = "警告 选中的文件无效"

["6284"]
desc = "警告 FCI 格式与 P2 指定的不符"

["6300"]
desc = "警告 鉴别失败"

["63Cx"]
desc = "警告 校验失败（x－允许重试次数）"

["6400"]
desc = "状态标志位没有变"

["6581"]
desc = "内存失败"

["6600"]
desc = "接收通讯超时"

["6601"]
desc = "接收字符奇偶错"

["6602"]
desc = "校验和不对"

["6603"]
desc = "警告 当前 DF 文件无 FCI"

["6604"]
desc = "警告 当前 DF 下无 SF 或 KF"

["6700"]
desc = "长度错误"

["6882"]
desc = "不支持安全报文"

["6900"]
desc = "不能处理"

["6901"]
desc = "命令不接受（无效状态）"

["6981"]
desc = "命令与文件结构不相容，当前文件非所需文件"

["6982"]
desc = "操作条件（AC）不满足，没有校验 PIN"

["6983"]
desc = "您的卡已被锁定"

["6984"]
desc = "随机数无效，引用的数据无效"

["6985"]
desc = "使用条件不满足"

["6986"]
desc = "不满足命令执行条件（不允许的命令，INS 有错）"

["6987"]
desc = "MAC 丢失"

["6988"]
desc = "MAC 不正确"

["698D"]
desc = "保留"

["6A80"]
desc = "数据域参数不正确"

["6A81"]
desc = "功能不支持；创建不允许；目录无效；应用锁定"

["6A82"]
desc = "该文件未找到"

["6A83"]
desc = "该记录未找到"

["6A84"]
desc = "文件预留空间不足"

["6A86"]
desc = "P1 或 P2 不正确"

["6A88"]
desc = "引用数据未找到"

["6B00"]
desc = "参数错误"

["6Cxx"]
desc = "Le 长度错误，实际长度是 xx"

["6D00"]
desc = "不支持的指令代码"

["6E00"]
desc = "不支持的类：CLA 有错"

["6E81"]
desc = "卡片已离开"

["6F00"]
desc = "数据无效"

["6F01"]
desc = "连接中断"

["9301"]
desc = "您的卡余额不足"

["9302"]
desc = "MAC2 错误"

["9303"]
desc = "应用被永久锁定"

["9401"]
desc = "您的卡余额不足"

["9402"]
desc = "交易计数器达到最大值"

["9403"]
desc = "密钥索引不支持"

["9406"]
desc = "所需 MAC 不可用"
